version: V1.0

server:
  port: ${PORT:8001}
  servlet:
    session:
      timeout: 21600s
    contextPath: /api


spring:
  datasource:
    url: jdbc:h2:mem:localhost
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
